export const ADD_LOCATION = 'ADD_LOCATION';
export const ADD_LINE = 'ADD_LINE';
export const API_CALL_PATHS = 'API_CALL_PATHS';
export const API_CALL_ELEVATION = 'API_CALL_ELEVATION';
export const CHANGE_TO_CLIP_PATH = 'CHANGE_TO_CLIP_PATH';
export const CLEAR_ROUTE = 'CLEAR_ROUTE';
export const CLOSE_ROUTE = 'CLOSE_ROUTE';
export const REMOVE_LATEST_POINT = 'REMOVE_LATEST_POINT';
export const SHOW_ELEVATION = 'SHOW_ELEVATION';
export const UPDATE_ELEVATION_DATA = 'UPDATE_ELEVATION_DATA';
export const UPDATE_TRANSPORTATION = 'UPDATE_TRANSPORTATION';
export const UPDATE_VIEWPORT = 'UPDATE_VIEWPORT';

//Authentication
export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_IN_USER = 'SIGN_IN_USER';
export const AUTH_USER = 'AUTH_USER';
