// MAP && ROUTES
export const ADD_LOCATION = 'ADD_LOCATION';
export const ADD_LINE = 'ADD_LINE';
export const API_CALL_PATHS = 'API_CALL_PATHS';
export const API_CALL_ELEVATION = 'API_CALL_ELEVATION';
export const CHANGE_TO_CLIP_PATH = 'CHANGE_TO_CLIP_PATH';
export const CLEAR_ROUTE = 'CLEAR_ROUTE';
export const CLOSE_ROUTE = 'CLOSE_ROUTE';
export const REMOVE_LATEST_POINT = 'REMOVE_LATEST_POINT';
export const SHOW_ELEVATION = 'SHOW_ELEVATION';
export const UPDATE_ELEVATION_DATA = 'UPDATE_ELEVATION_DATA';
export const UPDATE_TRANSPORTATION = 'UPDATE_TRANSPORTATION';
export const UPDATE_VIEWPORT = 'UPDATE_VIEWPORT';

//AUTHENTICATION
export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const LOAD_USER = 'LOAD_USER';
export const AUTH_USER = 'AUTH_USER';
export const SET_USERNAME = 'SET_USERNAME';
export const LOADING_USER = 'LOADING_USER';

//RUNNING ROUTES
export const SAVE_ROUTE = 'SAVE_ROUTE';
export const GET_ROUTES = 'GET_ROUTES';
export const ADD_ROUTE = 'ADD_ROUTE';
export const DELETE_ROUTE = 'DELETE_ROUTE';
export const DELETE_ROUTE_SUCCESS = 'DELETE_ROUTE_SUCCESS';
export const ADD_ALL_ROUTES = 'ADD_ALL_ROUTES';
export const CLEAR_ROUTES = 'CLEAR_ROUTES';
export const LOADING_ROUTES = 'LOADING_ROUTES';

//POPUP
export const NOTIFY_SUCCESS = 'NOTIFY_SUCCESS';
export const NOTIFY_FAILURE = 'NOTIFY_FAILURE';
export const CLOSE_POPUP = 'CLOSE_POPUP';

//RUNLOGS
export const LOG_RUN = 'LOG_RUN';
export const POPULATE_RUNLOG = 'POPULATE_RUNLOG';
export const GET_RUNS_BY_DATE = 'GET_RUNS_BY_DATE';
export const GET_RUNS_BY_DATE_SUCCESS = 'GET_RUNS_BY_DATE_SUCCESS';
export const GET_WEEKLY_RUNS = 'GET_WEEKLY_RUNS';
export const GET_WEEKLY_RUNS_SUCCESS = 'GET_WEEKLY_RUNS_SUCCESS';
export const LOG_RUN_SUCCESS = 'LOG_RUN_SUCCESS';
export const GET_RUNS_BY_MONTH = 'GET_RUNS_BY_MONTH';
export const GET_RUNS_BY_MONTH_SUCCESS = 'GET_RUNS_BY_MONTH_SUCCESS';

// GOAL
export const SET_GOAL = 'SET_GOAL';
export const SET_GOAL_SUCCESS = 'SET_GOAL_SUCCESS';
export const POPULATE_GOAL = 'POPULATE_GOAL';
